# SYNTAX TEST "Packages/Debian Syntax/Syntaxes/debian-debhelper.sublime-syntax"

# Debhelper install file
# <- punctuation.definition.comment.debian
#^^^^^^^^^^^^^^^^^^^^^^^^ comment.line.debian

usr/bin/backuppc
# <- string.unquoted.path.debian.debhelper
#  ^ punctuation.separator.path.debian.debhelper
#      ^ punctuation.separator.path.debian.debhelper

usr/share/doc/backuppc/*.html
# <- string.unquoted.path.debian.debhelper
#                     ^^^^^^^ string.unquoted.path.debian.debhelper

usr/lib/${DEB_HOST_MULTIARCH}/libbackuppc*.so.*
# <- string.unquoted.path.debian.debhelper
#    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ string.unquoted.path.debian.debhelper

${DEB_HOST_MULTIARCH}/lib*.so
#^ punctuation.definition.variable.begin.debian.debhelper
# ^^^^^^^^^^^^^^^^^^ variable.language.debian.debhelper
#                   ^ punctuation.definition.variable.end.debian.debhelper
#                        ^ keyword.operator.glob.debian.debhelper

usr/share/man/man?/*
# <- string.unquoted.path.debian.debhelper
#              ^^^^^ string.unquoted.path.debian.debhelper
