[DEFAULT]
pristine-tar = True
upstream-branch = upstream
debian-branch = debian/latest

[buildpackage]
export-dir = ../build-area/
tarball-dir = ../tarballs/

[import-orig]
merge-mode = replace
filter = [ '.gitignore', '.travis.yml' ]

[dch]
git-author = True
