name: Syntax Tests

on:
  push:
    paths:
      - '**.sublime-syntax'
      - '**/syntax_test*'
      - '**.tmPreferences'
  pull_request:
    paths:
      - '**.sublime-syntax'
      - '**/syntax_test*'
      - '**.tmPreferences'

jobs:
  syntax_tests:
    name: Syntax Tests (${{ matrix.build }})
    strategy:
      matrix:
        include:
          - build: latest
            packages: master
          - build: 3210
            packages: st3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run syntax tests
        uses: SublimeText/syntax-test-action@v2
        with:
          build: ${{ matrix.build }}
          default_packages: ${{ matrix.packages }}
